---
- 
# target where you need to play the playbook tomcat
  hosts: web1
  gather_facts: false
  vars:
    req_java: java-1.8.0-openjdk
    set_java: jre-1.8.0-openjdk
    req_tomcat_var: 8.5.61
    tomcat_url: https://downloads.apache.org/tomcat/tomcat-{{ req_tomcat_var.split('.')[0] }}/v{{ req_tomcat_var }}/bin/apache-tomcat-{{ req_tomcat_var-}}.tar.gz
  become: yes
  tasks:
    - name: update the repos
      yum:
        name: "*"
        state: latest
    - name: install required java
      yum:
        name: "{{ req_java }}"
        state: present
    - name: setting default path
      alternatives:
        name: java
        link: /usr/bin/java
        path: /usr/lib/jvm/{{ set_java }}/bin/java
    - name: Download required tomcat
      get_url:
        url: "{{ tomcat_url }}"
        dest: /usr/local
    - name: Extract downloaded tomcat
      unarchive:
        src: "/usr/local/apache-tomcat-{{ req_tomcat_var }}.tar.gz"
        dest: /usr/local
        remote_src: yes
    - name: Rename the tomcat home
      command: mv /usr/local/apache-tomcat-{{req_tomcat_var}} /usr/local/latest
    - name: replace server.xml
      template:
        src: server.xml.j2
        dest: /usr/local/latest/conf/server.xml
    - name: starting tomcat
      shell: nohup /usr/local/latest/bin/startup.sh &
