---
- 
# target where you need to play the playbook tomcat
  hosts: web1
  gather_facts: false
  vars:
    req_java: java-1.8.0-openjdk
    set_java: jre-1.8.0-openjdk
  become: yes
  tasks:
    - name: update the repos
      yum:
        name: "*"
        state: latest
    - name: install required java
      yum:
        name: "{{ req_java }}"
        state: present
    - name: setting default path
      alternatives:
        name: java
        link: /usr/bin/java
        path: /usr/lib/jvm/{{ set_java }}/bin/java
